Repository kelseyhightower/confd, pull requests merged in 2018-02, with the labels that each got.

#668 Add atoi function to template funcs and test
  docs/templates.md
  resource/template/template_funcs.go
  resource/template/template_test.go
Labels: resource/template

#661 Vault TLS certificates auth method
  backends/vault/client.go
Labels: enhancement

#665 backend/etcd: add scheme to srv discovered endpoints
  config.go
Labels: bug

#604 Redis Backend Updates: WatchPrefix Support, Hash Support, Standard Redis Key Naming Convention
  backends/client.go
  backends/config.go
  backends/redis/client.go
  config.go
  docs/command-line-flags.md
  integration/redis/test.sh
Labels: enhancement

#643 Add AppRole authN for Vault backend
  backends/client.go
  backends/config.go
  backends/vault/client.go
  config.go
  docs/command-line-flags.md
Labels: enhancement

#623 Add Kubernetes auth for Vault backend
  backends/client.go
  backends/config.go
  backends/vault/client.go
  config.go
  docs/command-line-flags.md
  docs/vault-kubernetes-auth.md
Labels: enhancement

#669 add parseBool to template_funcs
  resource/template/template_funcs.go
Labels: resource/template

#675 fix fileStat close when open failed on windows
  resource/template/fileStat_windows.go
Labels: bug

#674 Fix vendor name for logrus
  Gopkg.lock
  Gopkg.toml
  log/log.go
  vendor/github.com/sirupsen/logrus/.gitignore
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/CHANGELOG.md
  vendor/github.com/sirupsen/logrus/LICENSE
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/appveyor.yml
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/hooks.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_linux.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
Labels: bug
